[mysql]
host = 47.120.40.157
port = 3306
user = root
password = Shawn#6ge1
database = talktodata

[mysql_dev]
host = 47.120.40.157
port = 3306
user = root
password = Shawn#6ge1
database = talktodata_dev

[LLM_server]
api_key = sk-10ac90a6267a46ad83df797d65520494
model = qwen-plus
options = {"temperature": 0.3} 

[LLM_server_dev]
api_key = sk-10ac90a6267a46ad83df797d65520494
model = qwen-plus
options = {"temperature": 0.3} 

[VectorDB]
base_path = /root/app_files/TalkToData/data/vectordb/

[VectorDB_dev]
base_path = D:\shawn\Computer\git\Talk-To-Data\data\vectordb\
